# Welcome to Jekyll!
#

# Site settings
title: OpenArchive
title_image: https://open-archive.org/images/panopticonZoom1Sm.png
description: A free, open-source mobile application dedicated to maintaining the privacy, provenance, and preservation of your media.
#owner:  # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: info@open-archive.org
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://open-archive.org" # the base hostname & protocol for your site
twitter_username: "open_archive"
social:
  twitter: https://twitter.com/open_archive
  github: https://github.com/openarchive
  #linkedin-square: https://linkedin.com/in/<username>
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  email: info@open-archive.org
  #flickr:
  instagram: https://instagram.com/open__archive
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
